import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ChevronDownIcon,
  DownloadIcon,
  PencilIcon,
  RefreshCwIcon,
  SaveIcon,
  Share2Icon,
  SparklesIcon,
  TicketIcon,
  UsersIcon,
  WalletIcon } from
'lucide-react';
import { ItineraryTimeline, MapCard } from '../components/itinerary/Timeline';
import { BudgetCard, CommunityInsight, WeatherCard } from '../components/cards/ContentCards';
import { BookingFlow } from '../components/booking/BookingFlow';
import { Badge, Button, Card, Skeleton } from '../components/ui/Primitives';
import { useAtlas } from '../contexts/AtlasContext';
import { generateTripPlan, persistTripPlan } from '../services/atlasApi';
import { formatRange, inr } from '../utils/format';

export function ItineraryPage() {
  const { plan, setPlan, toast } = useAtlas();
  const [regenerating, setRegenerating] = useState(false);
  const [explanationOpen, setExplanationOpen] = useState(true);
  const [bookingOpen, setBookingOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    if (!plan) {
      generateTripPlan({
        destination: 'Goa',
        startDate: '2026-09-12',
        endDate: '2026-09-16',
        adults: 2,
        children: 0,
        interests: ['Beaches', 'Food', 'Culture'],
        transport: ['Flight', 'Local Transport'],
        accommodation: ['Hotel'],
        food: ['Local cuisine', 'Vegetarian'],
        accessibility: [],
        budget: 60000,
        currency: 'INR',
        flexibleBudget: true,
        notes: 'I prefer quiet places and want to avoid crowded tourist attractions.'
      }).then(setPlan);
    }
  }, [plan, setPlan]);

  if (!plan) {
    return (
      <div className="space-y-5">
        <Skeleton className="h-52" />
        <div className="grid gap-5 lg:grid-cols-[1fr_340px]">
          <Skeleton className="h-96" />
          <Skeleton className="h-96" />
        </div>
      </div>);

  }

  const regenerate = async () => {
    setRegenerating(true);
    const next = await generateTripPlan({
      destination: plan.destination,
      startDate: plan.startDate,
      endDate: plan.endDate,
      adults: plan.travelers,
      children: 0,
      interests: ['Nature', 'Food'],
      transport: ['Local Transport'],
      accommodation: ['Hotel'],
      food: ['Local cuisine'],
      accessibility: [],
      budget: plan.budget,
      currency: 'INR',
      flexibleBudget: true,
      notes: ''
    });
    setPlan(next);
    setRegenerating(false);
    toast({ title: 'Itinerary regenerated', description: 'Agents re-ran with the same constraints.', tone: 'success' });
  };

  const saveTrip = async () => {
    const token = localStorage.getItem('atlas_access_token');
    if (!token) {
      navigate('/login');
      return;
    }
    try {
      await persistTripPlan(plan, token);
      toast({ title: 'Trip saved', description: 'Added to My Trips.', tone: 'success' });
    } catch (error) {
      toast({ title: 'Could not save trip', description: error instanceof Error ? error.message : undefined, tone: 'error' });
    }
  };

  const summary = [
  { label: 'Estimated total cost', value: inr(plan.estimatedCost) },
  { label: 'Travel time', value: '6h 40m total' },
  { label: 'Accommodation', value: inr(plan.breakdown[0].value) },
  { label: 'Food', value: inr(plan.breakdown[2].value) },
  { label: 'Activities', value: inr(plan.breakdown[3].value) },
  { label: 'Remaining budget', value: inr(plan.budget - plan.estimatedCost) }];


  return (
    <div className="space-y-6">
      <Card className="overflow-hidden">
        <div className="relative h-44 sm:h-56">
          <img src={plan.image} alt={plan.destination} className="h-full w-full object-cover" />
          <div className="absolute inset-0 bg-slate-900/45" />
          <div className="absolute inset-x-0 bottom-0 p-6">
            <Badge tone="brand" className="bg-white/90 text-brand">
              <SparklesIcon className="h-3 w-3" /> Generated by 9 agents
            </Badge>
            <h1 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Your Personalized Trip</h1>
            <p className="mt-1 text-[14px] text-white/85">
              {plan.destination}, {plan.country} · {formatRange(plan.startDate, plan.endDate)} · {plan.travelers} travellers ·{' '}
              {inr(plan.budget)} budget
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2 border-t border-line p-4">
          <Button size="sm" icon={<TicketIcon className="h-3.5 w-3.5" />} onClick={() => setBookingOpen(true)}>
            Book this trip
          </Button>
          <Button size="sm" variant="secondary" icon={<PencilIcon className="h-3.5 w-3.5" />} onClick={() => navigate('/plan')}>
            Modify Trip
          </Button>
          <Button size="sm" variant="secondary" loading={regenerating} icon={<RefreshCwIcon className="h-3.5 w-3.5" />} onClick={regenerate}>
            Regenerate
          </Button>
          <Button
            size="sm"
            variant="secondary"
            icon={<SaveIcon className="h-3.5 w-3.5" />}
            onClick={saveTrip}>
            
            Save Trip
          </Button>
          <Button
            size="sm"
            variant="ghost"
            icon={<Share2Icon className="h-3.5 w-3.5" />}
            onClick={() => toast({ title: 'Share link copied', tone: 'success' })}>
            
            Share
          </Button>
          <Button
            size="sm"
            variant="ghost"
            icon={<DownloadIcon className="h-3.5 w-3.5" />}
            onClick={() => toast({ title: 'PDF generated', description: 'Your itinerary is downloading.', tone: 'success' })}>
            
            Download PDF
          </Button>
        </div>
      </Card>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {summary.map((s) =>
        <Card key={s.label} className="p-4">
            <p className="text-[12.5px] text-muted">{s.label}</p>
            <p className="mt-1 text-lg font-bold text-ink">{s.value}</p>
          </Card>
        )}
      </div>

      <Card className="overflow-hidden">
        <button
          onClick={() => setExplanationOpen((o) => !o)}
          aria-expanded={explanationOpen}
          className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left">
          
          <span>
            <span className="flex items-center gap-2 text-[15px] font-bold text-ink">
              <SparklesIcon className="h-4 w-4 text-brand" />
              Why ATLAS recommended this
            </span>
            <span className="mt-0.5 block text-[13px] text-muted">
              Seven reasoning signals from the planner, optimizer and constraint solver.
            </span>
          </span>
          <ChevronDownIcon className={`h-4.5 w-4.5 shrink-0 text-muted transition-transform ${explanationOpen ? 'rotate-180' : ''}`} />
        </button>
        <AnimatePresence initial={false}>
          {explanationOpen &&
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden border-t border-line">
            
              <ul className="grid gap-3 p-5 sm:grid-cols-2">
                {plan.reasoning.map((r) =>
              <li key={r.title} className="rounded-xl bg-canvas p-4">
                    <p className="text-[13.5px] font-semibold text-ink">{r.title}</p>
                    <p className="mt-1 text-[12.5px] leading-relaxed text-muted">{r.detail}</p>
                  </li>
              )}
              </ul>
            </motion.div>
          }
        </AnimatePresence>
      </Card>

      <div className="grid gap-5 lg:grid-cols-[1fr_340px]">
        <div className="order-2 space-y-5 lg:order-1">
          <h2 className="text-xl font-bold text-ink">Daily itinerary</h2>
          <ItineraryTimeline days={plan.days} />
        </div>
        <div className="order-1 space-y-5 lg:order-2">
          <MapCard
            destination={plan.destination}
            stops={['Airport → Hotel (12.4 km)', 'Hotel → Heritage walk (3.1 km)', 'Heritage walk → Dinner (5.1 km)']} />
          
          <WeatherCard days={plan.weather} />
          <BudgetCard budget={plan.budget} spent={plan.estimatedCost} breakdown={plan.breakdown} />
          <CommunityInsight
            title="Community verdict"
            quote="Travellers frequently mention this area for authentic local food and calmer evenings than the main strip."
            rating={4.7}
            reviews={5240}
            positives={['Authentic local food', 'Quiet mornings', 'Short travel distances']}
            concerns={['Busy on weekends', 'Limited late-night transport']} />
          
          <Card className="p-5">
            <div className="flex items-center gap-3">
              <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand/10 text-brand">
                <UsersIcon className="h-4.5 w-4.5" />
              </span>
              <div>
                <p className="text-[13.5px] font-semibold text-ink">{plan.travelers} travellers</p>
                <p className="text-[12.5px] text-muted">Pacing set to moderate with rest gaps</p>
              </div>
            </div>
            <div className="mt-4 flex items-center gap-3">
              <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-success/10 text-success">
                <WalletIcon className="h-4.5 w-4.5" />
              </span>
              <div>
                <p className="text-[13.5px] font-semibold text-ink">{inr(plan.budget - plan.estimatedCost)} buffer</p>
                <p className="text-[12.5px] text-muted">Held back for shopping and extras</p>
              </div>
            </div>
          </Card>
        </div>
      </div>

      <BookingFlow
        open={bookingOpen}
        onClose={() => setBookingOpen(false)}
        item={{
          title: `${plan.destination} · Personalized Trip Package`,
          type: 'Package',
          date: plan.startDate,
          price: plan.estimatedCost,
          travelers: plan.travelers,
          image: plan.image
        }} />
      
    </div>);

}